# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import master_pb2 as master__pb2


class IndexServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getFileDetails = channel.unary_unary(
                '/com.demo.jdfs.master.IndexService/getFileDetails',
                request_serializer=master__pb2.FileRequest.SerializeToString,
                response_deserializer=master__pb2.FileIndexResponse.FromString,
                )
        self.putFilesDetails = channel.unary_unary(
                '/com.demo.jdfs.master.IndexService/putFilesDetails',
                request_serializer=master__pb2.CreateOrEditFileRequest.SerializeToString,
                response_deserializer=master__pb2.FileIndexResponse.FromString,
                )


class IndexServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getFileDetails(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def putFilesDetails(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IndexServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getFileDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.getFileDetails,
                    request_deserializer=master__pb2.FileRequest.FromString,
                    response_serializer=master__pb2.FileIndexResponse.SerializeToString,
            ),
            'putFilesDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.putFilesDetails,
                    request_deserializer=master__pb2.CreateOrEditFileRequest.FromString,
                    response_serializer=master__pb2.FileIndexResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.demo.jdfs.master.IndexService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class IndexService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getFileDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.demo.jdfs.master.IndexService/getFileDetails',
            master__pb2.FileRequest.SerializeToString,
            master__pb2.FileIndexResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def putFilesDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.demo.jdfs.master.IndexService/putFilesDetails',
            master__pb2.CreateOrEditFileRequest.SerializeToString,
            master__pb2.FileIndexResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
